export {
  createSession,
  endSession,
  fetchLessonPlan,
  fetchLessons,
  fetchProgress,
  fetchWarmup,
  listSessions,
  regenerateLessonPlan,
  requestDebrief,
  requestHints,
  saveTurn,
  streamChat,
  synthesizeSpeech,
  transcribe,
  type ChatCallbacks,
  type ChatResult,
  type LessonPlanResult,
} from "./client"
